Algoritmo "DoisNQuadrado"

Var
   A, B: inteiro
   Anew, Bnew, Dif: real


Inicio
       Escreval("Descreva um número")
       Leia(A)
       Escreval("Descreva outro número")
       Leia(B)
       
       Anew <- A*A
       Bnew <- B*B
       Dif <- Anew - Bnew
       
       Escreval("O resultado da diferença do quadrado do primeiro número para ")
       Escreval("o segundo é:", Dif)
       


Fimalgoritmo