Algoritmo "NumerosSomados"

Var
   A, B, C, D: Inteiro
   P, S: real


Inicio
      Escreval("Digite um número")
      leia(A)
      Escreval("Digite outro número")
      Leia(B)
      Escreval("Mais um")
      Leia(C)
      Escreval("E pra finalizar o último")
      Leia(D)
      
      P <- A + C
      S <- B + D
      limpatela
      Escreval("A soma do primeiro número com o terceiro é", P)
      Escreval("A soma do segundo e do quarto número é de", S)


Fimalgoritmo